plugins = []
functionsDirectory = "/Users/sunder/projects/patra-darpan/web/netlify/functions"
functionsDirectoryOrigin = "config"
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/sunder/projects/patra-darpan/web"
publishOrigin = "config"
commandOrigin = "config"
command = "# no build command needed for static site"
functions = "/Users/sunder/projects/patra-darpan/web/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]