functionsDirectory = "/Users/sunder/projects/cahc/cahc-utils/ijhs-darpan/web/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "/Users/sunder/projects/cahc/cahc-utils/ijhs-darpan/web"
publishOrigin = "config"
commandOrigin = "ui"
base = "/Users/sunder/projects/cahc/cahc-utils/ijhs-darpan/web"
ignore = "exit 1"
functions = "/Users/sunder/projects/cahc/cahc-utils/ijhs-darpan/web/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
framework = "#static"
publish = "."

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"