"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const core = require("../web/assets/js/mcp-explorer-core.js");
const data = JSON.parse(fs.readFileSync("web/assets/data/mcp-ontology.json", "utf8"));
const model = core.index(data);
const id = "jyotisha:nakshatra_dhanishtha";
const state = { focus: id, roots: [id], type: "", relation: "", direction: "both", view: "neighbourhood" };
for (const query of ["धनिष्ठा", "श्रविष्ठा", "Dhanistha", "Śraviṣṭhā"]) assert.equal(core.search(model, query)[0].entity.id, id);
assert.equal(core.search(model, "a-name-not-in-the-ontology").length, 0);
const graph = core.graph(model, state);
assert.equal(graph.nodes.length, 4);
assert.equal(graph.edges.length, 3);
assert.equal(core.graph(model, { ...state, direction: "incoming" }).edges.length, 0);
const signs = core.graph(model, { ...state, type: "zodiac_sign" });
assert.equal(signs.nodes.length, 3); // Focus remains visible alongside the two matching neighbours.
assert.equal(signs.edges.length, 2);
assert.equal(core.graph(model, { ...state, relation: "located_in_veethi" }).edges.length, 1);
const expanded = core.graph(model, { ...state, roots: [id, "jyotisha:veethi_jaradgavi"] });
assert.ok(expanded.nodes.length > graph.nodes.length);
const author = core.relationships(model, "jyotisha:aryabhata");
const authorship = author.find(edge => edge.type === "authored_by");
assert.equal(authorship.direction, "incoming");
assert.equal(authorship.target.id, "jyotisha:work_aryabhatiya");
const work = core.relationships(model, authorship.target.id);
assert.equal(work.find(edge => edge.type === "composed_at").direction, "outgoing");
const all = core.graph(model, { ...state, view: "overview" });
assert.equal(all.nodes.length, data.entities.length);
assert.equal(all.edges.length, data.relations.length);
const subset = core.graph(model, { ...state, view: "overview", type: "person" });
assert.ok(subset.nodes.every(entity => entity.type === "person"));
assert.ok(subset.edges.every(edge => model.entities.get(edge.from).type === "person" && model.entities.get(edge.to).type === "person"));
assert.throws(() => core.index({ ...data, relations: [{ from: id, to: "missing" }] }), /Unknown relationship/);
console.log("MCP Explorer search, direction, canonical graph and expansion checks passed.");
